export const QUESTIONS_LIST_REQUEST = "QUESTIONS_LIST_REQUEST";
export const QUESTIONS_LIST_SUCCESS = "QUESTIONS_LIST_SUCCESS";
export const QUESTIONS_LIST_FAIL = "QUESTIONS_LIST_FAIL";

export const QUESTIONS_CREATE_REQUEST = "QUESTIONS_CREATE_REQUEST";
export const QUESTIONS_CREATE_SUCCESS = "QUESTIONS_CREATE_SUCCESS";
export const QUESTIONS_CREATE_FAIL = "QUESTIONS_CREATE_FAIL";
